version: "3.7"

services:
  go-main:
    build: server
    ports:
      - 8080:8080
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "postgres:5432", "--", "go", "run", "server_main.go"]
  
  postgres:
    build: postgres
    ports:
      - 6432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume:
