FROM postgres:14

ENV POSTGRES_USER mikhail
ENV POSTGRES_PASSWORD thisismyhair
ENV POSTGRES_DB cmkids

ADD database.sql backup.sql
ADD pg_restore.sh /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/pg_restore.sh

EXPOSE 5432/tcp
